start /b /wait Debug\embedded.exe sequences\gps_sequence_1.txt
start /b /wait Debug\embedded.exe sequences\gps_sequence_2.txt
start /b /wait Debug\embedded.exe sequences\gps_sequence_3.txt
start /b /wait Debug\embedded.exe sequences\gps_sequence_4.txt
start /b /wait Debug\embedded.exe sequences\gps_sequence_5.txt
start /b /wait Debug\embedded.exe sequences\gps_sequence_6.txt
start /b /wait Debug\embedded.exe sequences\gps_sequence_7.txt
start /b /wait Debug\embedded.exe sequences\gps_sequence_8.txt
start /b /wait Debug\embedded.exe sequences\gps_sequence_9.txt
start /b /wait Debug\embedded.exe sequences\gps_sequence_10.txt
start /b /wait Debug\embedded.exe sequences\gps_sequence_11.txt
start /b /wait Debug\embedded.exe sequences\gps_sequence_12.txt
start /b /wait Debug\embedded.exe sequences\gps_sequence_13.txt
start /b /wait Debug\embedded.exe sequences\gps_sequence_14.txt
start /b /wait Debug\embedded.exe sequences\gps_sequence_15.txt
start /b /wait Debug\embedded.exe sequences\gps_sequence_16.txt
start /b /wait Debug\embedded.exe sequences\gps_sequence_17.txt
start /b /wait Debug\embedded.exe sequences\gps_sequence_18.txt
start /b /wait Debug\embedded.exe sequences\gps_sequence_19.txt
start /b /wait Debug\embedded.exe sequences\gps_sequence_20.txt
start /b /wait Debug\embedded.exe sequences\gps_sequence_21.txt
start /b /wait Debug\embedded.exe sequences\gps_sequence_22.txt
start /b /wait Debug\embedded.exe sequences\gps_sequence_23.txt
start /b /wait Debug\embedded.exe sequences\gps_sequence_24.txt
start /b /wait Debug\embedded.exe sequences\gps_sequence_25.txt
start /b /wait Debug\embedded.exe sequences\gps_sequence_26.txt
start /b /wait Debug\embedded.exe sequences\gps_sequence_27.txt
start /b /wait Debug\embedded.exe sequences\gps_sequence_28.txt
start /b /wait Debug\embedded.exe sequences\gps_sequence_29.txt
start /b /wait Debug\embedded.exe sequences\gps_sequence_30.txt
pause
